sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mareksobierajski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mareksobierajski/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-150648441353'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"